### ISSUE TITLE
Problem with  objects in canvas

### ISSUE THREAD

**Issue by danieltomasz** [eliz-abeth/sandover#2]
Great theme! 

I  noticed a problem with the colours of the figures  on the canvas

![image](https://github.com/eliz-abeth/sandover/assets/7980381/e731664b-0a80-4dd2-954b-f6113aeaf8e7)

I interpret it as a bug, not as a feature :) 

Additionally, when I have a colourful border of the node before applying the theme, when I apply the theme, the border of the node disappears (excluding violet one).

**Comment by eliz-abeth** [comment]
just updated with a quick fix to this. for some reason obsidian only likes the theme's purple in canvas. will look into this later!

**Comment by danieltomasz** [comment]
@eliz-abeth just a quick brainstorming - could it be related to change in color of adminitions?

**Comment by eliz-abeth** [comment]
@danieltomasz just updated with the full fix -- you should be good to go with v1.0.7. let me know!

**Comment by danieltomasz** [comment]
@eliz-abeth  yes it works like expected, you might reorder back the colors if you wish :) 
the fix brought back the colors into note callouts/admonitions as well (as for me the issue might be closed)
