### ISSUE TITLE
Problem with diacritical marks

### ISSUE THREAD

**Issue by danieltomasz** [eliz-abeth/sandover#3]
For example, for  polish pangrams

```markdown
Pchnąć w tę łódź jeża lub ośm skrzyń fig.
Pójdź, kińże tę chmurność w głąb flaszy!.
```

I have problems when I  switch to the theme:

![image](https://github.com/eliz-abeth/sandover/assets/7980381/c2a766bd-07de-4506-b59d-e7064e7e08ef)`

But when I install `TT2020Base`and pick it manually, it works great.

![image](https://github.com/eliz-abeth/sandover/assets/7980381/59c883c1-c327-4cd9-be61-9d6b6ebaf3ce)

Could the reason for it be that the version of the font shipped with the theme doesn't have all  characters in order to make it more portable?

**Comment by eliz-abeth** [comment]
that's strange! it looks that way on my end too. the font is encoded in base64 within the theme. i'll look into this! thank you!

**Comment by danieltomasz** [comment]
there were some cases of base64 font not working as expected https://stackoverflow.com/questions/63074994/issues-with-embedded-icon-fonts-as-base64

**Comment by danieltomasz** [comment]
Dedicated Font converters sometimes drop  data (another story is encoding that should be specified for non-standards characters)
https://stackoverflow.com/questions/26867893/converting-and-rendering-web-fonts-to-base64-keep-original-look

**Comment by eliz-abeth** [comment]
i'm still working on this -- i tried the fontsquirrel settings that were suggested in the linked post, but that didn't work either

**Comment by eliz-abeth** [comment]
I am able to get the normal and normal italic fonts set up for diacritical marks. I was using TT2020's Style E for bold and bold italic, but this is the font that carries letter variants, so the base64 code is...immense. I might make a bold style out of the TT2020 base myself. The bold font, which is for h1 and inline note titles, wouldn't have dissimilar characters (see below for dissimilar chars) anymore in this case, but I think it's worth it, of course, for accommodating diacritical marks. I'm going to mess around with some ideas!

![IMG_9087](https://github.com/eliz-abeth/sandover/assets/66642379/837c8533-b8b1-4f57-b252-c046c9e2de62)

**Comment by eliz-abeth** [comment]
@danieltomasz alright...try now :)

**Comment by danieltomasz** [comment]
Works in my vault and in the sandbox vault!
