### ISSUE TITLE
Light theme and `Journals` plugin

### ISSUE THREAD

**Issue by danieltomasz** [eliz-abeth/sandover#4]
I am using `Journals` which is an replacement for `Calendar` plugins; 
https://github.com/srg-kostyrko/obsidian-journal
When I use sandover I see problems with the light theme- the dots symbolising entries for specific days aren't visible in the light theme
![image](https://github.com/eliz-abeth/sandover/assets/7980381/1b5b77b0-b926-4a51-8499-86e926b9a50e)
while in dark theme everything is ok
![image](https://github.com/eliz-abeth/sandover/assets/7980381/d36f96d7-8f2f-4f92-ac1f-019c907c4fa1)

I can create a issue at the plugin page, but so far only sandover  theme had problem with day-dots in light theme, so I thought maybe I can start here; 

In principle, the day-dots should  have a color of the accent color used through the app both in light and dark theme. The plugin seems to use `--text-accent` for background variable  within `div.journal.note.marker` https://github.com/srg-kostyrko/obsidian-journal/blob/faf62fd0ec12c1ecf53d411b281003d4d24c393a/styles.css#L320
this works in vanilla obsidian and dark mode, but not in 'Sandover' light mode (`div.journal.note.marker` doesnt seems  to have `background` variable in the light mode, but in dark mode does)

**Comment by eliz-abeth** [comment]
new update should fix this problem! :)

**Comment by danieltomasz** [comment]
Issue fixed :)

**Comment by danieltomasz** [comment]
Seems that one of latest releases, probably `2.0.4` reintroduced the problem

**Comment by eliz-abeth** [comment]
should be fixed now!

**Comment by danieltomasz** [comment]
fixed!
