### ISSUE TITLE
Bulletpoint markers  in dark theme are invisible in live preview/reading mode

### ISSUE THREAD

**Issue by danieltomasz** [eliz-abeth/sandover#5]
Bulletpoints in dark theme seems to be black (invisible on the dark backround)

text from Obsidian sandbox within light and dark theme (Sandover v. 1.0.7)

``` markdown
## I’m interested in Obsidian

First of all, tell me a little bit about what's your experience with note-taking apps like?

- [[No prior experience|I have no prior experience]]

- [[From standard note-taking|I’ve used note-taking apps like Evernote and OneNote]]

- [[From plain-text note-taking|I have used plain-text based apps]]

```

![image](https://github.com/eliz-abeth/sandover/assets/7980381/6016da68-550f-4fe4-ae9a-1cfe8b4cec1d)

![image](https://github.com/eliz-abeth/sandover/assets/7980381/4cffbabd-5a4a-4d3a-b95a-2e1bada169ae)

**Comment by eliz-abeth** [comment]
thanks for finding this and letting me know! the new update should have it fixed.

**Comment by danieltomasz** [comment]
issue fixed :)
