### ISSUE TITLE
Highlight in light theme

### ISSUE THREAD

**Issue by danieltomasz** [eliz-abeth/sandover#6]
The highlight '==test highlight==' doesn't seem to work in light theme, while dark theme seems to be ok.

Sandover v.1.0.9

**Comment by eliz-abeth** [comment]
oops! sorry about that. it should be fixed now.

**Comment by danieltomasz** [comment]
the fix is working, but the version included in the zip in the release is `1.0.6` , I downloaded the working version `2.0.2` manually

**Comment by danieltomasz** [comment]
Seems that `2.0.4` reintroduced the problem with the `==` highlight in light theme

**Comment by eliz-abeth** [comment]
should be good now!

**Comment by danieltomasz** [comment]
fixed!
