### ISSUE TITLE
Wrong version in the released zip file - `manifest.json` showing `1.0.6` instead of `2.0.2`

### ISSUE THREAD

**Issue by danieltomasz** [eliz-abeth/sandover#7]
the zipped files to download have wrong version in `json.file` - thats the reason that  Obsidian Themes shows 1.0.6 as the latest version.

**Comment by danieltomasz** [comment]
It appears that zip contains bad version, I downloaded the latest version manually from the release page

**Comment by eliz-abeth** [comment]
OMG. thanks for letting me know, and very sorry for this problem. i just pushed through 2.0.3 and made sure manifest etc was updated properly. i'm not sure if there is a delay before the version updates in obsidian themes. i'll keep an eye on it.

**Comment by danieltomasz** [comment]
@eliz-abeth do not worry, and again thanks for such a great theme! It's actually quite a common error (at least among Obsidian plugin developers) to include the wrong number/version in the release. :) 

One small thing I noticed: the separate download files have version `2.0.3` but the files in zip   and tar have `2.0.2`

**Comment by danieltomasz** [comment]
hi @eliz-abeth  I found the source of the problem the themes doesnt update - with the bump to 2.0 version you bumped `"minAppVersion": "2.0.3",` but this  should refer to  minimal Obsidian version, not the theme , it could be just `1.0.0` or `1.5.12`  if you want to support only recent releases,  for example  Minimal  theme has support up to 1.5.4

**Comment by eliz-abeth** [comment]
omg. thank you! it should be all fixed now.

**Comment by danieltomasz** [comment]
thanks for quick reactions, maintaining the public theme/plugin isn't easy 
I also reopened some old issues. it seems there was some regressions in the light version of the theme

**Comment by eliz-abeth** [comment]
of course!! i know it's so frustrating when things aren't working properly so i'm sorry it keeps happening. this is my first time even working with CSS so i'm learning a lot as i go!

plus, i use obsidian with this theme every day for my dissertation research, so i'm really invested in making it function properly (and this is a great form of procrastination!)

**Comment by danieltomasz** [comment]
Everything seems to be fixed now :) Finding bugs and creating  GitHub issues is another form of procrastination from writing dissertation :) Thanks  again for the theme and good luck with your research!
